# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jxMlG3qZ9QY7opmwdRq3LaM0q6yMBHW
"""



def bestMove:
  BestScore=float('-inf')
  for i in range(3):
      for j in range(3:)
          if (board[i][j]==''):
              board[i][j]=ai
              score=minimax(board,0 ,false)
              board[i][j]=''
              if(score >BestScore):
                 BestScore= score
                 move={i,j}







  board[move.i][move.j]=ai
  currentPlayer=human

scores={
  x:1
  o:-1
  tie:0


}

ai='x'
human='o'

def minimax(board ,depth,isMaximizing):
  result=checkWinner()
if result is not None:
  return score= scores[result]




if (isMaximizing):
    BestScore=float(-inf)
     for i in range(3):
         for j in range(3):
            if (board[i][j]==''):
                board[i][j]=ai
                score=minimax(board,depth+1,false)
                board[i][j]=''
                BestScore=max(score,BestScore)





        return BestScore




else:
    BestScore=float('inf')
       for i in range (3):
        for j in range (3):
            if (board[i][j]==''):
                board[i][j]=human
                score=minimax(board,depth+1,true)
                board[i][j]=''
                BestScore=min(score,BestScore)







        return BestScore